version: "3"
services:
  api1:
    container_name: api1
    build: ./helloworldapi
    ports:
      - 3001:3000
    environment:
      MESSAGE: ${MESSAGE_01}

  api2:
    container_name: api2
    build: ./helloworldapi
    ports:
      - 3000:3000
    environment:
      MESSAGE: ${MESSAGE_02}

  api3:
    container_name: api3
    build: ./helloworldapi
    ports:
      - 3002:3000
    environment:
      MESSAGE: ${MESSAGE_03}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRESS_DB: mydatabase

